test_batch_size: 64
lr: 0.001

target_lr: 0.2

momentum: 0.9
decay: 0.0005

retrain_no_times: 2
model: resnet

sampling_dirichlet: true
dirichlet_alpha: 0.5

# file names of the images
poison_type: wall

# manually chosen images for tests
poison_images_test:
  - 3934
  - 12336
  - 36848
  - 40713
  - 41706

poison_images:
  - 330
  - 568
  - 30560
  - 30696
  - 33105
  - 33615
  - 33907

poison_label_swaps: [0, 0, 2]
poison_label_swap: 2
size_of_secret_dataset: 500
random_compromise: false

retrain_poison: 30

poison_lr: 0.0005
poison_momentum: 0.9
poison_decay: 0.005
poison_step_lr: true
data_folder: ../data

0_poison_pattern: [[0, 4], [0, 5], [0, 6], [1, 4], [2, 4], [2, 5], [2, 6], [3, 4]]
1_poison_pattern: [[0, 9], [1, 9], [2, 9], [3, 9], [3, 10], [3, 11]]
2_poison_pattern: [[0, 15], [1, 14], [1, 16], [2, 14], [2, 15], [2, 16], [3, 14], [3, 16]]
3_poison_pattern: [[0, 19], [0, 20], [0, 21], [1, 20], [2, 20], [3, 19], [3, 20], [3, 21]]

